collection = set()
collection.add(1)
collection.add(2)
collection.add(2)
print(collection)
collection.remove(1)
print(collection)
print(len(collection))
collection.clear()
collection = {"Hello", 54, 78, 3, "Ankit"}
collection.pop()
print(collection)